### ISSUE TITLE
Timeout on api and website

### ISSUE THREAD

**Issue by clayderson** [crafatar/crafatar#254]
Any explanation for what's happening with the API?

**Comment by jomo** [comment]
I've already had someone else reporting issues (also from Brazil). I can't see any issues with the website from here.
Can you specify what exactly the issue is?

Is the issue IPv4 or IPv6, or both? Does ping work? Is the error constant or affects just some requests?

The output of `curl -v` or `--trace-ascii` would be helpful. Also if you could provide a pcap file (using Wireshark or tcpdump) that would make finding the issue easier.

**Comment by clayderson** [comment]
Thanks for answering!

Interesting to know that this does not occur elsewhere, as I am in weeks with this problem. I tested using IPv4. I do not have IPv6 support. Ping works normally.

ping crafatar.com
```
PING crafatar.com (104.31.112.168): 56 data bytes
64 bytes from 104.31.112.168: icmp_seq=0 ttl=53 time=96.826 ms
64 bytes from 104.31.112.168: icmp_seq=1 ttl=53 time=94.273 ms
64 bytes from 104.31.112.168: icmp_seq=2 ttl=53 time=95.854 ms
64 bytes from 104.31.112.168: icmp_seq=3 ttl=53 time=94.226 ms
64 bytes from 104.31.112.168: icmp_seq=4 ttl=53 time=94.499 ms
64 bytes from 104.31.112.168: icmp_seq=5 ttl=53 time=94.047 ms
64 bytes from 104.31.112.168: icmp_seq=6 ttl=53 time=94.026 ms
64 bytes from 104.31.112.168: icmp_seq=7 ttl=53 time=94.243 ms
```

traceroute crafatar.com
```
traceroute: Warning: crafatar.com has multiple addresses; using 104.31.112.168
traceroute to crafatar.com (104.31.112.168), 64 hops max, 52 byte packets
 1  192.168.0.1 (192.168.0.1)  2.648 ms  4.906 ms  1.495 ms
 2  static-168-0-52-6.interligadosnet.com.br (168.0.52.6)  1.523 ms  1.514 ms  2.003 ms
 3  172.20.6.1 (172.20.6.1)  2.829 ms  1.371 ms  1.452 ms
 4  static-168-0-52-89.interligadosnet.com.br (168.0.52.89)  2.482 ms  2.291 ms  20.503 ms
 5  177.36.12.246 (177.36.12.246)  4.814 ms  32.177 ms  6.518 ms
 6  * * *
 7  206.41.108.18 (206.41.108.18)  99.965 ms  95.714 ms  113.222 ms
 8  104.31.112.168 (104.31.112.168)  105.054 ms  103.739 ms  105.564 ms
```

curl -v https://crafatar.com/renders/body/12ccd852-6599-34ed-a0db-c0d932428b4c\?overlay\&default\=MHF_Steve\&scale\=4

curl first attempt
```
*   Trying 104.31.113.168...
* TCP_NODELAY set
* Connected to crafatar.com (104.31.113.168) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to crafatar.com:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to crafatar.com:443
```

curl third attempt
```
*   Trying 104.31.112.168...
* TCP_NODELAY set
* Connected to crafatar.com (104.31.112.168) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to crafatar.com:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to crafatar.com:443 
```

[crafatarpcap.pcap.zip](https://github.com/crafatar/crafatar/files/2873542/crafatarpcap.pcap.zip)

**Comment by clayderson** [comment]
I tried without ssl

![captura de tela 2019-02-17 20 59 01](https://user-images.githubusercontent.com/15388584/52921535-df3a6300-32f6-11e9-8336-5270b2482744.png)

curl -v http://crafatar.com/renders/body/invaliduuid

```
➜  ~ date
Dom 17 Fev 2019 21:02:13 -03
➜  ~ curl -v http://crafatar.com/renders/body/invaliduuid
*   Trying 104.31.112.168...
* TCP_NODELAY set
* Connected to crafatar.com (104.31.112.168) port 80 (#0)
> GET /renders/body/invaliduuid HTTP/1.1
> Host: crafatar.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* stopped the pause stream!
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
➜  ~ date                                                
Dom 17 Fev 2019 21:03:04 -03
➜  ~ 
```

**Comment by jomo** [comment]
Thanks. I'm still looking into this. Could you capture more single http (not https) request as pcap?

```sh
curl --trace-ascii - http://crafatar.com/debug/<some-random-string>
```

I'm still not sure if this is an issue on our side, but so far I couldn't find anything that would suggest it is. Will probably have to contact Cloudflare to look into this.

**Comment by clayderson** [comment]
I'm noticing it's a bit random. Sometimes a response with "not found" is returned quickly and following expected behavior. Sometimes the problem we are discussing occurs. In fact, it's more conducive to the problem, maybe a 70% chance.

curl --trace-ascii - http://crafatar.com/debug/aotearoa

```
== Info:   Trying 104.31.112.168...
== Info: TCP_NODELAY set
== Info: Connected to crafatar.com (104.31.112.168) port 80 (#0)
=> Send header, 90 bytes (0x5a)
0000: GET /debug/aotearoa HTTP/1.1
001e: Host: crafatar.com
0032: User-Agent: curl/7.54.0
004b: Accept: */*
0058: 
<= Recv header, 24 bytes (0x18)
0000: HTTP/1.1 404 Not Found
<= Recv header, 37 bytes (0x25)
0000: Date: Tue, 19 Feb 2019 04:27:26 GMT
<= Recv header, 26 bytes (0x1a)
0000: Content-Type: text/plain
<= Recv header, 28 bytes (0x1c)
0000: Transfer-Encoding: chunked
<= Recv header, 24 bytes (0x18)
0000: Connection: keep-alive
<= Recv header, 143 bytes (0x8f)
0000: Set-Cookie: __cfduid=d9f88bda8eec6088f4e0c72940f3983e51550550446
0040: ; expires=Wed, 19-Feb-20 04:27:26 GMT; path=/; domain=.crafatar.
0080: com; HttpOnly
<= Recv header, 37 bytes (0x25)
0000: Cache-Control: public, max-age=3600
<= Recv header, 18 bytes (0x12)
0000: Response-Time: 0
<= Recv header, 27 bytes (0x1b)
0000: X-Request-ID: kodr7g5dxdk
<= Recv header, 32 bytes (0x20)
0000: Access-Control-Allow-Origin: *
<= Recv header, 28 bytes (0x1c)
0000: X-Storage-Type: user error
<= Recv header, 23 bytes (0x17)
0000: CF-Cache-Status: MISS
<= Recv header, 40 bytes (0x28)
0000: Expires: Tue, 19 Feb 2019 05:27:26 GMT
<= Recv header, 33 bytes (0x21)
0000: X-Content-Type-Options: nosniff
<= Recv header, 20 bytes (0x14)
0000: Server: cloudflare
<= Recv header, 30 bytes (0x1e)
0000: CF-RAY: 4ab5fb21bf4ac895-MIA
<= Recv header, 2 bytes (0x2)
0000: 
<= Recv data, 19 bytes (0x13)
0000: 9
0003: Not found
000e: 0
0011: 
Not found== Info: Connection #0 to host crafatar.com left intact
```

[crafatardebug.pcap.zip](https://github.com/crafatar/crafatar/files/2878302/crafatardebug.pcap.zip)

**Comment by jomo** [comment]
Thanks for the effort. That request obviously worked fine, I was looking for the capture of a request that did _not work_, sorry for not being clear about this.

**Comment by jomo** [comment]
I noticed that Cloudflare stats show that traffic from Brazil drastically declined over the last month, which I took as an indicator that requests aren't reaching Cloudflare properly and filed an issue with them. I'll follow up with any updates here.

**Comment by clayderson** [comment]
Sorry for my mistake. In the last few minutes I was trying to get a new failed report but I could not. I noticed that all the requests are working. The problem was solved?

**Comment by RickyB98** [comment]
Some people are still getting the issue on our website. I'm in Italy and I can load avatars just fine, but I have reports from France, UK and US saying that they can't load them. The website depends quite heavily on those avatars so apparently the malfunction is also disrupting other features of the website.

**Comment by jomo** [comment]
If anyone with issues could please provide a .pcap file for a failed request for each:

- http://crafatar.com/cdn-cgi/trace (http)
- https://crafatar.com/cdn-cgi/trace (https)

Please use `curl`, or an "Incognito" / "Private" browser window to prevent cached results and HSTS.

If one those requests actually works (while other Crafatar links do not), please let me know!

----

If you (or your users) are not familiar with creating a pcap file, close all programs except an Incognito browser window and follow [this article](https://www.howtogeek.com/104278/how-to-use-wireshark-to-capture-filter-and-inspect-packets/) on how to use Wireshark. You can also email the file to `githubⓐjomo.tv` if you don't want to paste publicly or don't have a GitHub account.

----

Unfortunately it's hard for me to debug this issue without being able to reproduce it myself, so I depend on your help. I'm in contact with Cloudflare, but quite understandably they're a bit slow to respond for support requests from free accounts. (We can't pay $200/Month for support from the -15$/y income ;)

**Comment by clayderson** [comment]
Would not it be the case to migrate to another CloudFlare account? You would get new nameservers and new IPs.

**Comment by jomo** [comment]
For everyone affected:

Cloudflare is asking for the output of https://www.cloudflare.com/cdn-cgi/trace from affected users. If it doesn't work, please provide your external IP address ([Google "What's my IP"](https://google.com/search?q=what%27s%20my%20ip)).

Also could you provide a traceroute using TCP port 80 and 443?

```sh
mtr -rwc30 -T -P 80 104.31.112.168
mtr -rwc30 -T -P 443 104.31.112.168
```

**Comment by jomo** [comment]
There haven't been any complaints in a while.
